version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.18.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-dependencies
          command: yarn install --immutable
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: run-tests
          command: yarn test
  run_test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.18.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: run-tests
          command: yarn test
workflows:
  build_yarn:
    jobs:
      - build
  test_yarn:
    jobs:
      - run_test
