name: Check Workflow update
on: 
  pull_request:
    branches:
      - main
  issues:
    types: [opened, edited]
  push:
    branches:
      - main
jobs:
  build:
    name: Installation and Testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: yarn
    - name: Run Jest
      run: yarn test
    - name: Status Giphy
      uses: jzweifel/pr-status-giphy-action@master
      env:
        GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
