name: GitHub Actions Demo
on: [push]
jobs:
  build:
    name: Push Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: yarn
    - name: Run Jest
      run: yarn test