name: Check Workflow update
on: 
  pull_request:
    branches:
      - main
  issues:
    types: [opened, edited]
  push:
    branches:
      - main
jobs:
  build:
    name: Installation and Testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: yarn
    - name: Run Jest
      run: yarn test

name: Gif It
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Installation and Testing
    runs-on: ubuntu-latest
    steps:
    - name: Ramsey GIFifier
      # You may pin to the exact commit or the version.
      # uses: ethan-dowler/ramsey-gififier@9da89a13ff3efe7304a98ddc9c964c47b7846ef8
      uses: ethan-dowler/ramsey-gififier@0.4
      with:
        # Github token for the repository.
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  
