name: Check Workflow update
on: 
  pull_request:
    branches:
      - main
  issues:
    types: [opened, edited]
  push:
    branches:
      - main
jobs:
  build:
    name: Installation and Testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: yarn
    - name: Run Jest
      run: yarn test
    - name: Passing all
      if: ${{ success() }}
      uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: "Good job!"
        check_for_duplicate_msg: false  # OPTIONAL 
    - name: Something failed
      if: ${{ success() }}
      uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: "An oopsie happened"
        check_for_duplicate_msg: false  # OPTIONAL 
    - name: PR Status Giphy
      uses: jzweifel/pr-status-giphy-action@master
      env:
        GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
